erDiagram
    CATEGORIAS {
        INTEGER ID_CATEGORIA PK
        VARCHAR NOMBRE
    }
    CLIENTES {
        VARCHAR APELLIDO
        VARCHAR EMAIL
        INTEGER ID_CLIENTE PK
        INTEGER ID_ZONA FK
        VARCHAR NOMBRE
    }
    CLIENTES_HIB {
        VARCHAR EMAIL
        INTEGER ID_CLIENTE PK FK
        COM_EJEMPLO_MODEL_ZONAHIBERNATE ID_ZONA FK
        VARCHAR NOMBRE
    }
    CUSTOMERS {
        INTEGER C_ID PK
        VARCHAR NAME
    }
    PEDIDOS {
        DATE FECHA
        INTEGER ID_CLIENTE FK
        INTEGER ID_PEDIDO PK FK
        UNKNOWN MONTO
    }
    PEDIDOS_HIB {
        DATE FECHA
        INTEGER ID_CLIENTE FK
        INTEGER ID_PEDIDO PK FK
        DECIMAL MONTO
    }
    PEDIDO_PRODUCTOS {
        UNKNOWN ID_PEDIDO FK
        UNKNOWN ID_PRODUCTO FK
    }
    PEDIDO_PRODUCTOS_HIB {
        UNKNOWN ID_PEDIDO FK
    }
    PRODUCTOS {
        INTEGER ID_CATEGORIA FK
        INTEGER ID_PRODUCTO PK
        VARCHAR NOMBRE
        UNKNOWN PRECIO
    }
    PRODUCTOS_HIB {
        INTEGER ID_PRODUCTO PK
        VARCHAR NOMBRE
    }
    PRODUCTS {
        VARCHAR PRODUCT_CODE
        INTEGER PRODUCT_ID PK
    }
    TBL_LEGACY {
        INTEGER ID PK
    }
    ZONAS {
        INTEGER ID_ZONA PK
        VARCHAR NOMBRE
    }
    APP_ORDERS {
        INTEGER CUSTOMER_ID FK
        VARCHAR DESCRIPTION
        INTEGER ORDER_ID PK FK
        VARCHAR STATUS
    }
    APP_ORDER_PRODUCT {
        UNKNOWN ORDER_ID FK
        UNKNOWN PRODUCT_ID FK
    }
    IESS_DOCTOR {
        INTEGER DOCTOR_ID FK
        INTEGER ID PK
    }
    IESS_DOCTOR_PATIENT {
        UNKNOWN DOCTOR_ID FK
        UNKNOWN PATIENT_ID FK
    }
    IESS_HOSPITAL {
        NUMBER_10_ ID PK
        VARCHAR2_100_ NAME
    }
    IESS_PATIENT {
        NUMBER_10_ HOSPITAL_ID FK
        NUMBER_10_ ID PK
        VARCHAR MOBILE
        VARCHAR2_80_ NAME
    }
    CLIENTES ||--o{ PEDIDOS : "pedidos"
    CLIENTES }o--|| ZONAS : "zona"
    CLIENTES_HIB ||--o{ PEDIDOS_HIB : "pedidos"
    CUSTOMERS ||--o{ APP_ORDERS : "orders"
    PEDIDOS }o--|| CLIENTES : "cliente"
    PEDIDOS ||--o{ PRODUCTOS : "productos"
    PEDIDOS_HIB }o--|| CLIENTES_HIB : "cliente"
    PEDIDOS_HIB ||--o{ PRODUCTOS_HIB : "productos"
    PEDIDO_PRODUCTOS }o--|| PEDIDOS : "ID_PEDIDO"
    PEDIDO_PRODUCTOS }o--|| PRODUCTOS : "ID_PRODUCTO"
    PEDIDO_PRODUCTOS_HIB }o--|| PEDIDOS_HIB : "ID_PEDIDO"
    PRODUCTOS ||--|| CATEGORIAS : "categoria"
    APP_ORDERS }o--|| CUSTOMERS : "customer"
    APP_ORDERS ||--o{ PRODUCTS : "products"
    APP_ORDER_PRODUCT }o--|| APP_ORDERS : "ORDER_ID"
    APP_ORDER_PRODUCT }o--|| PRODUCTS : "PRODUCT_ID"
    IESS_DOCTOR ||--o{ IESS_PATIENT : "patients"
    IESS_DOCTOR_PATIENT }o--|| IESS_DOCTOR : "DOCTOR_ID"
    IESS_DOCTOR_PATIENT }o--|| IESS_PATIENT : "PATIENT_ID"
    IESS_PATIENT }o--|| IESS_HOSPITAL : "HOSPITAL_ID"
